cmake_minimum_required(VERSION 3.22)

project("PokeEngineWorkspace" VERSION 0.1.0 LANGUAGES C CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

if (MSVC)
    add_compile_options(/GR- /EHs-)
else()
    add_compile_options(-fno-rtti)
endif()

add_subdirectory("Poke")
add_subdirectory("PokeEngineEditor")

set_property(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR} PROPERTY VS_STARTUP_PROJECT PokeEngineEditor)